### ISSUE TITLE
Ansible 9 support - Conditional is marked as unsafe, and cannot be evaluated

### ISSUE THREAD

**Issue by kuduka** [justin-p/ansible-role-wincom#6]
With newer versions of Ansible this role fails running:

    "msg": "The conditional check 'wincom_required_psmodule is defined' failed. The error was: Conditional is marked as unsafe, and cannot be evaluated."

As a workaround I've changed this assert to:

```
- name: Assert mandatory variables have been set
    ansible.builtin.assert:
      that:
        - wincom_required_psmodule is defined
        - wincom_service_delayed is defined
        .....
```
Or:

```
  - name: Assert mandatory variables have been set
    fail:
      msg: "Variable '{{ item }}' is not defined"
    with_items:
        - wincom_required_psmodule
        - wincom_service_delayed
        .....
```
No idea what would be a better option, same issue with pdc role as well.

Could you please check it out?
